# This is a basic workflow to help you get started with Actions

name: Update {renv} components

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pages: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv/
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true


      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true

      # Runs a single command using the runners shell
      - name: Update renv
        shell: Rscript {0}
        run: |
          renv::record(paste0("renv@", packageVersion("renv")))
          renv::restore(library = renv::paths$library())
          renv::update(library = renv::paths$library())
          renv::snapshot()

      - name: Push back to main
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m '[actions] update submodules :rocket:' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

